[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cc3"
version = "0.1.0"
description = "Graph objects and algorithms for general use"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyglet",
    "numpy"
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["cc3"]
