WINDOW_WIDTH = "WINDOW_WIDTH"
WINDOW_HEIGHT = "WINDOW_HEIGHT"
WINDOW_FPS = "WINDOW_FPS"
WINDOW_ANTIALIAS = "WINDOW_ANTIALIAS"

COLOUR_BG = "COLOUR_BG"
COLOUR_FG = "COLOUR_FG"
COLOUR_VERTEX = "COLOUR_VERTEX"
COLOUR_OUTLINE = "COLOUR_OUTLINE"
COLOUR_OUTLINE_SELECTED = "COLOUR_OUTLINE_SELECTED"

VERTEX_RADIUS = "VERTEX_RADIUS"
VERTEX_QUALITY = "VERTEX_QUALITY"
VERTEX_OUTLINE = "VERTEX_OUTLINE"

PHYSICS_ESCAPE_FORCE = "PHYSICS_ESCAPE_FORCE"
PHYSICS_REPULSION = "PHYSICS_REPULSION"
PHYSICS_DAMPING = "PHYSICS_DAMPING"
PHYSICS_SPRING_STIFFNESS = "PHYSICS_SPRING_STIFFNESS"
PHYSICS_SPRING_LENGTH = "PHYSICS_SPRING_LENGTH"

class GraphError(Exception):
    """base level flag for graph related exceptions"""

class VertexError(GraphError):
    """flag for vertex access failures (e.g. vertex 5 not in graph of size 3)"""

class EdgeError(GraphError):
    """flag for edge access failures (e.g. trying to remove an edge that doesn't exist)"""